### ISSUE TITLE
GPU Not Found after crash (GTX1050, windows)

### ISSUE THREAD

**Issue by wssunn** [plaidml/plaidml#377]
I have installed plaidml and it all worked. Brilliant toolkit! I used GTX 1050 for this installation.

Today I was training my network but I decided to do keyboard interrupt on jupyter notebook. After then GTX 1050 device cannot be found. Later I unistalled the entire plaidml and tried to reinstall using pip and plaidml-setup however still no device can be found during plaidml-setup. (In fact the only device can be found is llvm_cpu). I have checked my computer and GPU is still functioning (I played games). 

I wonder whether there is any documents that automatically records crashes and prevents the crashed device from discovered again.

Thank you very much!

![image](https://user-images.githubusercontent.com/34838378/61781217-8a1af400-ae36-11e9-9960-b769b31f1475.png)

**Comment by IIIBlueberry** [comment]
Has you try rebooting your pc?

**Comment by dgkutnic** [comment]
Is your GPU being recognized if you run [clinfo](https://github.com/Oblomov/clinfo)? Having OpenCL recognize your GPU would be a prerequisite for PlaidML being able to recognize it as a device.

**Comment by wssunn** [comment]
No it is not recognised. I tried reinstall the miniconda, reboot the system and the problem is solved. Thank you.

**Comment by dgkutnic** [comment]
Thanks for following up! Closing this as your issue has been resolved.
